### ISSUE TITLE
tickInTime is not exported in the autogenerated file

### ISSUE THREAD

**Issue by Xterionix** [Blockception/BC-Minecraft-Bedrock-Types#135]
https://github.com/Blockception/BC-Minecraft-Bedrock-Types/blob/main/src/minecraft/index.ts

**Comment by DaanV2** [comment]
Aah yeah, I disable the auto generation of those files, and now do it manually 😅

**Comment by Xterionix** [comment]
Should I make a pr to fix this or will you fix it?

**Comment by DaanV2** [comment]
If you want, wont be able to do much myself this weekend
